### ISSUE TITLE
Resetting Files and Saving is no longer possible. Please bring these features back.

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#16]
We write in the book about resetting files via Options->Reset Files in the editor.

**Comment by tomitrescak** [comment]
Yes, that menu has moved to another location. We might need to update it. I sent you email about it previously.

**Comment by antonwsu** [comment]
I can't find the email. Where was it moved to?

**Comment by antonwsu** [comment]
Found it at the ... menu at the top

**Comment by tomitrescak** [comment]
Justin

I'm @tomitrescak<mailto:reply@reply.github.com>

I cannot find my tomastrescak account

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]

From: Justin Mahlberg <J.Mahlberg@westernsydney.edu.au>
Sent: Thursday, 18 February 2021 5:40 PM
To: Tomas Trescak <T.Trescak@westernsydney.edu.au>
Subject: RE: Experiment

Hey Tomas,

Are you on Gitlab? I'm finding a @tomastrescak, is that you? If so I'll add you!

Justin

From: Tomas Trescak
Sent: Thursday, February 18, 2021 3:16 PM
To: Justin Mahlberg; Tamara Watson; John Cass
Subject: RE: Experiment

Justin

Can you maybe give me access to the repo so that I can upload changes myself?

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]

From: Justin Mahlberg <J.Mahlberg@westernsydney.edu.au<mailto:J.Mahlberg@westernsydney.edu.au>>
Sent: Thursday, 18 February 2021 2:34 PM
To: Tomas Trescak <T.Trescak@westernsydney.edu.au<mailto:T.Trescak@westernsydney.edu.au>>; Tamara Watson <T.Watson@westernsydney.edu.au<mailto:T.Watson@westernsydney.edu.au>>; John Cass <J.Cass@westernsydney.edu.au<mailto:J.Cass@westernsydney.edu.au>>
Subject: RE: Experiment

Hey Tomas,

Apologies for the delays -- that's my bad. Tamara and I have been working behind the scenes to get the student recruitment portal (SONA) set up to run the semester. But I've been slammed so I've only just gotten to working on the code to  communicate between SONA and Pavlovia this morning.

Did you say previously that you've modified the experiment code? Can you please upload the files either here or on github so I can work on the most recent version of the experiment?

As for a meeting, I can only meet Monday next week (sorry).

Cheers
Justin

From: Tomas Trescak
Sent: Thursday, February 18, 2021 12:17 PM
To: Tamara Watson; Justin Mahlberg; John Cass
Subject: Experiment

Dears

Is there anything I can do to run the experiment?
Can we also meet soon?
I'd like to discuss the second phase strategy.

Kind rgards

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]

**Comment by tomitrescak** [comment]
Hey Tomas,

That looks like it's a github account, rather than a gitlab account. This morning  I tried to set it up so gitlab and github could be integrated and we could work out of github but its slightly more complicated than I was anticipating, so I'm yet to figure it out
Justin

From: Tomas Trescak
Sent: Thursday, February 18, 2021 8:53 PM
To: Justin Mahlberg; tomitrescak/clara-support
Subject: RE: Experiment

Justin

I'm @tomitrescak<mailto:reply@reply.github.com>

I cannot find my tomastrescak account

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]

From: Justin Mahlberg <J.Mahlberg@westernsydney.edu.au<mailto:J.Mahlberg@westernsydney.edu.au>>
Sent: Thursday, 18 February 2021 5:40 PM
To: Tomas Trescak <T.Trescak@westernsydney.edu.au<mailto:T.Trescak@westernsydney.edu.au>>
Subject: RE: Experiment

Hey Tomas,

Are you on Gitlab? I'm finding a @tomastrescak, is that you? If so I'll add you!

Justin

From: Tomas Trescak
Sent: Thursday, February 18, 2021 3:16 PM
To: Justin Mahlberg; Tamara Watson; John Cass
Subject: RE: Experiment

Justin

Can you maybe give me access to the repo so that I can upload changes myself?

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]

From: Justin Mahlberg <J.Mahlberg@westernsydney.edu.au<mailto:J.Mahlberg@westernsydney.edu.au>>
Sent: Thursday, 18 February 2021 2:34 PM
To: Tomas Trescak <T.Trescak@westernsydney.edu.au<mailto:T.Trescak@westernsydney.edu.au>>; Tamara Watson <T.Watson@westernsydney.edu.au<mailto:T.Watson@westernsydney.edu.au>>; John Cass <J.Cass@westernsydney.edu.au<mailto:J.Cass@westernsydney.edu.au>>
Subject: RE: Experiment

Hey Tomas,

Apologies for the delays -- that's my bad. Tamara and I have been working behind the scenes to get the student recruitment portal (SONA) set up to run the semester. But I've been slammed so I've only just gotten to working on the code to  communicate between SONA and Pavlovia this morning.

Did you say previously that you've modified the experiment code? Can you please upload the files either here or on github so I can work on the most recent version of the experiment?

As for a meeting, I can only meet Monday next week (sorry).

Cheers
Justin

From: Tomas Trescak
Sent: Thursday, February 18, 2021 12:17 PM
To: Tamara Watson; Justin Mahlberg; John Cass
Subject: Experiment

Dears

Is there anything I can do to run the experiment?
Can we also meet soon?
I'd like to discuss the second phase strategy.

Kind rgards

Dr Tomas Trescak
Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751

P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: t.trescak@westernsydney.edu.au<mailto:t.trescak@westernsydney.edu.au>

We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D'harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

[UWS LOGO]
