### ISSUE TITLE
Can't see exercises in Book -> Chapter 2 when logged in with westernsydney.edu.au account

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#23]
This is my student account that also has "Book" membership.
<img width="1094" alt="Screen Shot 2021-02-16 at 4 53 52 pm" src="https://user-images.githubusercontent.com/26546072/108023980-c7c61a00-7077-11eb-84d4-4f07f9da260c.png">

**Comment by antonwsu** [comment]
For some reason I see them in Safari, but not in Google Chrome. This is probably because I was logging in on Safari with my admin account. I've changed the organisation to "Book" for this schedule a few minutes ago.

**Comment by antonwsu** [comment]
This issue keeps reappearing occasionally in different browsers. It's usually solved with refresh, but will be confusing for students if this persists.

**Comment by tomitrescak** [comment]
Hey, the reason why you do not see the exercises is because they belong to a different organisation and they are hidden. 

![image](https://user-images.githubusercontent.com/2682705/108149267-9193a380-7126-11eb-8271-1d2c9746f572.png)

You need to fix the permissions in order to access them by the book user.

The reason why you were seeing them in one browser and not the other is exactly what you wrote. Since you were logged in as admin, the exercises were cached in your browser and you were able to see them. While this would never happen to the user I understand that it is confusing. As a result I now reset the cache upon logout and the behaviour is as you would expect.
