### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by tomitrescak** [tomitrescak/clara-support#34]
@antonwsu @dean-p do you find the navigation bar useful at all? It looks good but is a bit in the way.

![image](https://user-images.githubusercontent.com/2682705/108465241-c2fea180-72d5-11eb-9e91-d2cc96870886.png)

**Comment by Dean-P** [comment]
I use it all the time, personally. It does look out of place though since the boards are centred. It could be moved to another section or given its own divider to separate it from the board.

It is also worth noting that in the Major Assignment, there is no back button so the navigation bar is to only way to get out of the exercise view (other than hitting back in the browser):
![ma](https://user-images.githubusercontent.com/9068794/108466029-1fae8c00-72d7-11eb-8c42-c78a7fc5b54c.png)

**Comment by antonwsu** [comment]
@tomitrescak I also use it all the time.

**Comment by tomitrescak** [comment]
Ok, thanks
