### ISSUE TITLE
Book Schedule issues on Stage

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#75]
1. Chapter 2 problems don't work.
2. Chapter 5 -> Clara Makes Friends (Solution): complains about readString().
3. Chapter 6 -> Line in the Middle (Solution): complains about readInt().
4. Chapter 7 -> Bug Navigation (Solution): many errors in getToNextDesiredPos()
5. Chapter 7 -> Random Walk (Solution): complains about 0.75.
6. Chapter 8 -> Jumping Clara Solution: does not compile
7. Chapter 9->  Clara_MakesFriends_Array ( Solution ): complains about readString().
8. Chapter 9 -> Game of Life: does not compile
9. Chapter 10 -> all problems: do not compile

**Comment by tomitrescak** [comment]
- [x] Chapter 2 problems don't work.
- [x] Chapter 5 -> Clara Makes Friends (Solution): complains about readString().
- [x] Chapter 6 -> Line in the Middle (Solution): complains about readInt().
- [x] Chapter 7 -> Bug Navigation (Solution): many errors in getToNextDesiredPos()
- [x] Chapter 7 -> Random Walk (Solution): complains about 0.75.
- [x] Chapter 8 -> Jumping Clara Solution: does not compile
- [x] Chapter 9-> Clara_MakesFriends_Array ( Solution ): complains about readString().
- [x] Chapter 9 -> Game of Life: does not compile
- [x]  Chapter 10 -> all problems: do not compile


I am checking this all locally and these are my notes how to fix this on live once we start the integration Also, @anronwsu check out what was the issue

> Chapter 2 problems don't work.

You no longer need to implement custom act method handling as this is supported natively. You either specify your `run` method or `act` method. To stop the execution you need to call `Engine.stop()`

```
public void stop() {
   Engine.stop();
}
```

**INTEGRATION**: Replace Character Methods

> Chapter 5 and 6 and 9

Don't ask me why, but I removed these methods. They are back in and will HAVE TO BE COPIED doring integration

**INTEGRATION**: Add the new World definition

> Chapter 7 (Bug Navigation (Solution))

This might have been fixed with with what I have already done, but all seems to work fine for me 

> Chapter 7 (Random Walk (Solution))

Fixed, I managed to forgot to implement float literals 😊

> Chapter 8 -> Jumping Clara Solution: does not compile

I have renamed `__context` and `__db` to `Engine` and we should slowly phase it out. But I added the backward support for it for these cases.

> Chapter 9 -> Game of Life: does not compile

Will have to replace `Character` and `Clara`. It seems to work fine now

> Chapter 10

Will have to replace the affected files

**Comment by tomitrescak** [comment]
Ok, seems like I am ready, you will have to re-test the chapter 10, but once you give me a GO I can flip it to live and we'll just have to doule check everything .

**Comment by tomitrescak** [comment]
Ok, all seems to work
