### ISSUE TITLE
No cancel button when adding practicals/problems

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#92]
It happens frequently that I'm trying to add a practical or problem and then realise that I need more information. So I want to cancel, have a look at what it was offering me (e.g AUT 2018) and then come back and add it again. There is, however, no way to cancel. One you start searching for a practical to add - it will be added.

**Comment by tomitrescak** [comment]
There is a "Close" button in the bottom right part of the list. You need to click that. But, since you couldn't find it, I'm sure the next person would not find it as well so I changed the UX to this:

![image](https://user-images.githubusercontent.com/2682705/127266162-63d4796d-2dce-40a0-8712-bdb8742e31b8.png)
